/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package com.mycompany.primerapractica.frames;

import com.mycompany.primerapractica.manejadores.ManejadorNuevaApuesta;
import javax.swing.JOptionPane;

/**
 *
 * @author manu
 */
public class IngresoResultados extends javax.swing.JDialog {
    
    private ManejadorNuevaApuesta manejador;
    boolean ingresoValido = false;
    /**
     * Creates new form IngresoResultados
     */
    public IngresoResultados(java.awt.Frame parent, boolean modal, ManejadorNuevaApuesta manejador ) {
        super(parent, modal);
        initComponents();
        
        this.manejador = manejador;
        
    }

    public boolean isIngresoValido() {
        return ingresoValido;
    }

    public void setIngresoValido(boolean ingresoValido) {
        this.ingresoValido = ingresoValido;
    }
    
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        hechoButton = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        GanadorLabel = new javax.swing.JLabel();
        posicionTextField9 = new javax.swing.JTextField();
        posicionTextField7 = new javax.swing.JTextField();
        posicionTextField3 = new javax.swing.JTextField();
        terceLabel = new javax.swing.JLabel();
        posicionTextField5 = new javax.swing.JTextField();
        novenoLabel = new javax.swing.JLabel();
        decimoLabel = new javax.swing.JLabel();
        segundoLabel = new javax.swing.JLabel();
        posicionTextField10 = new javax.swing.JTextField();
        posicionTextField8 = new javax.swing.JTextField();
        posicionTextField1 = new javax.swing.JTextField();
        posicionTextField4 = new javax.swing.JTextField();
        posicionTextField2 = new javax.swing.JTextField();
        cuartoLabel = new javax.swing.JLabel();
        quintoLabel = new javax.swing.JLabel();
        septimoLabel = new javax.swing.JLabel();
        octavoLabel = new javax.swing.JLabel();
        sextoLabel = new javax.swing.JLabel();
        posicionTextField6 = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jLabel1.setText("Numero del caballo");

        jLabel4.setText("Posicion final:");

        jLabel3.setText("Posicion final:");

        hechoButton.setText("Hecho");
        hechoButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                hechoButtonActionPerformed(evt);
            }
        });

        jLabel2.setText("Numero del caballo");

        jLabel5.setText("Por favor ingrese, en orden, los resultados de la carrera");

        GanadorLabel.setText("Primero:");

        terceLabel.setText("Tercero:");

        novenoLabel.setText("Noveno:");

        decimoLabel.setText("Décimo:");

        segundoLabel.setText("Segundo:");

        cuartoLabel.setText("Cuarto:");

        quintoLabel.setText("Quinto:");

        septimoLabel.setText("Séptimo:");

        octavoLabel.setText("Octavo:");

        sextoLabel.setText("Sexto:");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 46, Short.MAX_VALUE)
                .addComponent(jLabel4)
                .addGap(18, 18, 18)
                .addComponent(jLabel1)
                .addGap(37, 37, 37))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(253, 253, 253)
                        .addComponent(hechoButton, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(74, 74, 74)
                        .addComponent(jLabel5)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel1Layout.createSequentialGroup()
                    .addGap(55, 55, 55)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(quintoLabel)
                        .addComponent(cuartoLabel)
                        .addComponent(terceLabel)
                        .addComponent(GanadorLabel)
                        .addComponent(segundoLabel))
                    .addGap(28, 28, 28)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(posicionTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(posicionTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(posicionTextField3, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(posicionTextField4, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(posicionTextField5, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(sextoLabel, javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(septimoLabel, javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(octavoLabel, javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(novenoLabel, javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(decimoLabel, javax.swing.GroupLayout.Alignment.TRAILING))
                    .addGap(29, 29, 29)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(posicionTextField6, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(posicionTextField8, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(posicionTextField9, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(posicionTextField10, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(posicionTextField7, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGap(55, 55, 55)))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel5)
                .addGap(22, 22, 22)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jLabel3)
                    .addComponent(jLabel2)
                    .addComponent(jLabel4))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 235, Short.MAX_VALUE)
                .addComponent(hechoButton)
                .addGap(24, 24, 24))
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel1Layout.createSequentialGroup()
                    .addGap(79, 79, 79)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(GanadorLabel)
                                .addComponent(posicionTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(posicionTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(segundoLabel))
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(terceLabel)
                                .addComponent(posicionTextField3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(cuartoLabel)
                                .addComponent(posicionTextField4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(quintoLabel)
                                .addComponent(posicionTextField5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(sextoLabel)
                                .addComponent(posicionTextField6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(septimoLabel)
                                .addComponent(posicionTextField7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(octavoLabel)
                                .addComponent(posicionTextField8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(novenoLabel)
                                .addComponent(posicionTextField9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(decimoLabel)
                                .addComponent(posicionTextField10, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addContainerGap(79, Short.MAX_VALUE)))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void hechoButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_hechoButtonActionPerformed
        // TODO add your handling code here:
           try {
            boolean x1 = this.manejador.evaluarNumerosIngresados(this.posicionTextField1, 0);
            boolean x2 =this.manejador.evaluarNumerosIngresados(this.posicionTextField2, 1);
            boolean x3 =this.manejador.evaluarNumerosIngresados(this.posicionTextField3, 2);
            boolean x4 =this.manejador.evaluarNumerosIngresados(this.posicionTextField4, 3);
            boolean x5 =this.manejador.evaluarNumerosIngresados(this.posicionTextField5, 4);
            boolean x6 =this.manejador.evaluarNumerosIngresados(this.posicionTextField6, 5);
            boolean x7 =this.manejador.evaluarNumerosIngresados(this.posicionTextField7, 6);
            boolean x8 = this.manejador.evaluarNumerosIngresados(this.posicionTextField8, 7);
            boolean x9 = this.manejador.evaluarNumerosIngresados(this.posicionTextField9, 8);
            boolean x10=this.manejador.evaluarNumerosIngresados(this.posicionTextField10, 9);
            
            
            if(!x1||!x2||!x3||!x4||!x5||!x6||!x7||!x8||!x9||!x10){
                JOptionPane.showMessageDialog(null, "Por favor solo ingrese numeros enteros de 1 a 10 dentro de las casillas y que no eseten repetidos");
                manejador.llenarNumerosDisponibles();
                
            }else {
                this.manejador.setResultados(manejador.getOrdenNumeros());
                this.ingresoValido = true;
                dispose();
            }
            
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Por favor solo ingrese numeros enteros de 1 a 10 dentro de las casillas y que no eseten repetidos");
        }
       
    }//GEN-LAST:event_hechoButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(IngresoResultados.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(IngresoResultados.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(IngresoResultados.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(IngresoResultados.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                IngresoResultados dialog = new IngresoResultados(new javax.swing.JFrame(), true, null);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel GanadorLabel;
    private javax.swing.JLabel cuartoLabel;
    private javax.swing.JLabel decimoLabel;
    private javax.swing.JButton hechoButton;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel novenoLabel;
    private javax.swing.JLabel octavoLabel;
    private javax.swing.JTextField posicionTextField1;
    private javax.swing.JTextField posicionTextField10;
    private javax.swing.JTextField posicionTextField2;
    private javax.swing.JTextField posicionTextField3;
    private javax.swing.JTextField posicionTextField4;
    private javax.swing.JTextField posicionTextField5;
    private javax.swing.JTextField posicionTextField6;
    private javax.swing.JTextField posicionTextField7;
    private javax.swing.JTextField posicionTextField8;
    private javax.swing.JTextField posicionTextField9;
    private javax.swing.JLabel quintoLabel;
    private javax.swing.JLabel segundoLabel;
    private javax.swing.JLabel septimoLabel;
    private javax.swing.JLabel sextoLabel;
    private javax.swing.JLabel terceLabel;
    // End of variables declaration//GEN-END:variables
}
