/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package com.mycompany.primerapractica.frames;

/**
 *
 * @author manu
 */
public class IngresoResultados extends javax.swing.JDialog {

    /**
     * Creates new form IngresoResultados
     */
    public IngresoResultados(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        numerosBox9 = new javax.swing.JComboBox<>();
        segundoLabel = new javax.swing.JLabel();
        terceLabel = new javax.swing.JLabel();
        octavoLabel = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        hechoButton = new javax.swing.JButton();
        numerosBox3 = new javax.swing.JComboBox<>();
        novenoLabel = new javax.swing.JLabel();
        numerosBox6 = new javax.swing.JComboBox<>();
        cuartoLabel = new javax.swing.JLabel();
        quintoLabel = new javax.swing.JLabel();
        numerosBox5 = new javax.swing.JComboBox<>();
        sextoLabel = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        numerosBox8 = new javax.swing.JComboBox<>();
        numerosBox1 = new javax.swing.JComboBox<>();
        decimoLabel = new javax.swing.JLabel();
        GanadorLabel = new javax.swing.JLabel();
        numerosBox7 = new javax.swing.JComboBox<>();
        septimoLabel = new javax.swing.JLabel();
        numerosBox4 = new javax.swing.JComboBox<>();
        numerosBox10 = new javax.swing.JComboBox<>();
        numerosBox2 = new javax.swing.JComboBox<>();
        jLabel5 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jLabel1.setText("Numero del caballo");

        jLabel4.setText("Posicion final:");

        numerosBox9.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        numerosBox9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                numerosBox9ActionPerformed(evt);
            }
        });

        segundoLabel.setText("Segundo:");

        terceLabel.setText("Tercero:");

        octavoLabel.setText("Octavo:");

        jLabel3.setText("Posicion final:");

        hechoButton.setText("Hecho");
        hechoButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                hechoButtonActionPerformed(evt);
            }
        });

        numerosBox3.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        numerosBox3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                numerosBox3ActionPerformed(evt);
            }
        });

        novenoLabel.setText("Noveno:");

        numerosBox6.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        numerosBox6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                numerosBox6ActionPerformed(evt);
            }
        });

        cuartoLabel.setText("Cuarto:");

        quintoLabel.setText("Quinto:");

        numerosBox5.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        numerosBox5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                numerosBox5ActionPerformed(evt);
            }
        });

        sextoLabel.setText("Sexto:");

        jLabel2.setText("Numero del caballo");

        numerosBox8.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        numerosBox8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                numerosBox8ActionPerformed(evt);
            }
        });

        numerosBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        numerosBox1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                numerosBox1ActionPerformed(evt);
            }
        });

        decimoLabel.setText("Décimo:");

        GanadorLabel.setText("Primero:");

        numerosBox7.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        numerosBox7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                numerosBox7ActionPerformed(evt);
            }
        });

        septimoLabel.setText("Séptimo:");

        numerosBox4.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        numerosBox4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                numerosBox4ActionPerformed(evt);
            }
        });

        numerosBox10.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        numerosBox10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                numerosBox10ActionPerformed(evt);
            }
        });

        numerosBox2.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        numerosBox2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                numerosBox2ActionPerformed(evt);
            }
        });

        jLabel5.setText("Por favor ingrese, en orden, los resultados de la carrera");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel4)
                .addGap(18, 18, 18)
                .addComponent(jLabel1)
                .addGap(37, 37, 37))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(48, 48, 48)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(segundoLabel)
                        .addGap(18, 18, 18)
                        .addComponent(numerosBox2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(terceLabel)
                        .addGap(18, 18, 18)
                        .addComponent(numerosBox3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(cuartoLabel)
                        .addGap(18, 18, 18)
                        .addComponent(numerosBox4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(quintoLabel)
                        .addGap(18, 18, 18)
                        .addComponent(numerosBox5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(GanadorLabel)
                        .addGap(18, 18, 18)
                        .addComponent(numerosBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 116, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(septimoLabel)
                        .addGap(18, 18, 18)
                        .addComponent(numerosBox7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(sextoLabel)
                        .addGap(18, 18, 18)
                        .addComponent(numerosBox6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(octavoLabel)
                        .addGap(18, 18, 18)
                        .addComponent(numerosBox8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(novenoLabel)
                        .addGap(18, 18, 18)
                        .addComponent(numerosBox9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(decimoLabel)
                        .addGap(18, 18, 18)
                        .addComponent(numerosBox10, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(74, 74, 74))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(253, 253, 253)
                        .addComponent(hechoButton, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(74, 74, 74)
                        .addComponent(jLabel5)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel5)
                .addGap(22, 22, 22)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jLabel3)
                    .addComponent(jLabel2)
                    .addComponent(jLabel4))
                .addGap(26, 26, 26)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(GanadorLabel)
                            .addComponent(numerosBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(segundoLabel)
                            .addComponent(numerosBox2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(terceLabel)
                            .addComponent(numerosBox3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(cuartoLabel)
                            .addComponent(numerosBox4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(quintoLabel)
                            .addComponent(numerosBox5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(sextoLabel)
                            .addComponent(numerosBox6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(septimoLabel)
                            .addComponent(numerosBox7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(octavoLabel)
                            .addComponent(numerosBox8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(novenoLabel)
                            .addComponent(numerosBox9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(decimoLabel)
                            .addComponent(numerosBox10, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 10, Short.MAX_VALUE)
                .addComponent(hechoButton)
                .addGap(24, 24, 24))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void numerosBox9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_numerosBox9ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_numerosBox9ActionPerformed

    private void hechoButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_hechoButtonActionPerformed
        // TODO add your handling code here:

        dispose();
    }//GEN-LAST:event_hechoButtonActionPerformed

    private void numerosBox3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_numerosBox3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_numerosBox3ActionPerformed

    private void numerosBox6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_numerosBox6ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_numerosBox6ActionPerformed

    private void numerosBox5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_numerosBox5ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_numerosBox5ActionPerformed

    private void numerosBox8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_numerosBox8ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_numerosBox8ActionPerformed

    private void numerosBox1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_numerosBox1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_numerosBox1ActionPerformed

    private void numerosBox7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_numerosBox7ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_numerosBox7ActionPerformed

    private void numerosBox4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_numerosBox4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_numerosBox4ActionPerformed

    private void numerosBox10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_numerosBox10ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_numerosBox10ActionPerformed

    private void numerosBox2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_numerosBox2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_numerosBox2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(IngresoResultados.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(IngresoResultados.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(IngresoResultados.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(IngresoResultados.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                IngresoResultados dialog = new IngresoResultados(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel GanadorLabel;
    private javax.swing.JLabel cuartoLabel;
    private javax.swing.JLabel decimoLabel;
    private javax.swing.JButton hechoButton;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel novenoLabel;
    private javax.swing.JComboBox<String> numerosBox1;
    private javax.swing.JComboBox<String> numerosBox10;
    private javax.swing.JComboBox<String> numerosBox2;
    private javax.swing.JComboBox<String> numerosBox3;
    private javax.swing.JComboBox<String> numerosBox4;
    private javax.swing.JComboBox<String> numerosBox5;
    private javax.swing.JComboBox<String> numerosBox6;
    private javax.swing.JComboBox<String> numerosBox7;
    private javax.swing.JComboBox<String> numerosBox8;
    private javax.swing.JComboBox<String> numerosBox9;
    private javax.swing.JLabel octavoLabel;
    private javax.swing.JLabel quintoLabel;
    private javax.swing.JLabel segundoLabel;
    private javax.swing.JLabel septimoLabel;
    private javax.swing.JLabel sextoLabel;
    private javax.swing.JLabel terceLabel;
    // End of variables declaration//GEN-END:variables
}
